# Generated by Django 5.0.7 on 2024-07-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Job",
            new_name="Landing",
        ),
    ]
